In [1]:
# Resource https://www.learnpytorch.io/00_pytorch_fundamentals/

In [6]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1


In [100]:
tensor = torch.rand(3, 4)
tensor

tensor([[0.5055, 0.3590, 0.3339, 0.2354],
        [0.5862, 0.3591, 0.2871, 0.0278],
        [0.6963, 0.5218, 0.6517, 0.7639]])

In [102]:
# Stack tensors on top of each other

In [104]:
x = torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [106]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [108]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)

In [110]:
z[:, 0] = 5
z, x
x_reshaped = x
x_reshaped

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [112]:
# Stack tensors on top of each other

In [114]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [116]:
x_stacked.shape

torch.Size([4, 9])

In [118]:
# x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [120]:
# torch.squeeze() - removes all signel dimensions from a target tensor

In [122]:
x = torch.zeros(2,1,2,1,2)

In [124]:
x.size()

torch.Size([2, 1, 2, 1, 2])

In [126]:
x_reshaped

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [128]:
x_reshaped.shape

torch.Size([9])

In [130]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [132]:
x_reshaped.squeeze().shape

torch.Size([9])

In [136]:
print(f"previous tensor : {x_reshaped} {x_reshaped.shape}")

previous tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])


In [138]:
# Remote extra dimentions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"previous tensor : {x_squeezed} {x_squeezed.shape}")

previous tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])


In [158]:
# UnSqueeze, adds single/extra dimention to a target tensor
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [160]:
x_unsqueezed.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [162]:
# torch permute, rearranges the dimensions of a target tensor in a specified order 

In [166]:
x_original = torch.rand(size=(224, 224, 3)) #{height width, colour_channels}
x_original

tensor([[[0.6126, 0.1183, 0.7006],
         [0.7714, 0.9695, 0.6598],
         [0.5767, 0.5573, 0.0662],
         ...,
         [0.3464, 0.7585, 0.9757],
         [0.1533, 0.3273, 0.5336],
         [0.5136, 0.4688, 0.1998]],

        [[0.3879, 0.0894, 0.5836],
         [0.4260, 0.8265, 0.6197],
         [0.6712, 0.6680, 0.3527],
         ...,
         [0.4735, 0.9866, 0.0812],
         [0.1517, 0.8906, 0.6959],
         [0.8489, 0.8399, 0.9329]],

        [[0.8633, 0.7218, 0.7419],
         [0.9804, 0.0216, 0.0588],
         [0.9594, 0.9945, 0.3261],
         ...,
         [0.9660, 0.9889, 0.6794],
         [0.9219, 0.2128, 0.5393],
         [0.8330, 0.2532, 0.1187]],

        ...,

        [[0.6162, 0.5186, 0.8582],
         [0.2484, 0.3044, 0.5830],
         [0.0507, 0.7899, 0.8873],
         ...,
         [0.8011, 0.3310, 0.5569],
         [0.8454, 0.6511, 0.5502],
         [0.0622, 0.9741, 0.7125]],

        [[0.1856, 0.0485, 0.1389],
         [0.7379, 0.2530, 0.4741],
         [0.

In [178]:
# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [180]:
x_original[:, :, 0] = 1

In [182]:
x_original

tensor([[[1.0000, 0.1183, 0.7006],
         [1.0000, 0.9695, 0.6598],
         [1.0000, 0.5573, 0.0662],
         ...,
         [1.0000, 0.7585, 0.9757],
         [1.0000, 0.3273, 0.5336],
         [1.0000, 0.4688, 0.1998]],

        [[1.0000, 0.0894, 0.5836],
         [1.0000, 0.8265, 0.6197],
         [1.0000, 0.6680, 0.3527],
         ...,
         [1.0000, 0.9866, 0.0812],
         [1.0000, 0.8906, 0.6959],
         [1.0000, 0.8399, 0.9329]],

        [[1.0000, 0.7218, 0.7419],
         [1.0000, 0.0216, 0.0588],
         [1.0000, 0.9945, 0.3261],
         ...,
         [1.0000, 0.9889, 0.6794],
         [1.0000, 0.2128, 0.5393],
         [1.0000, 0.2532, 0.1187]],

        ...,

        [[1.0000, 0.5186, 0.8582],
         [1.0000, 0.3044, 0.5830],
         [1.0000, 0.7899, 0.8873],
         ...,
         [1.0000, 0.3310, 0.5569],
         [1.0000, 0.6511, 0.5502],
         [1.0000, 0.9741, 0.7125]],

        [[1.0000, 0.0485, 0.1389],
         [1.0000, 0.2530, 0.4741],
         [1.

In [184]:
x_permuted

tensor([[[1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         ...,
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 1.0000]],

        [[0.1183, 0.9695, 0.5573,  ..., 0.7585, 0.3273, 0.4688],
         [0.0894, 0.8265, 0.6680,  ..., 0.9866, 0.8906, 0.8399],
         [0.7218, 0.0216, 0.9945,  ..., 0.9889, 0.2128, 0.2532],
         ...,
         [0.5186, 0.3044, 0.7899,  ..., 0.3310, 0.6511, 0.9741],
         [0.0485, 0.2530, 0.6420,  ..., 0.8715, 0.1982, 0.2908],
         [0.4907, 0.4829, 0.9482,  ..., 0.9013, 0.9600, 0.4938]],

        [[0.7006, 0.6598, 0.0662,  ..., 0.9757, 0.5336, 0.1998],
         [0.5836, 0.6197, 0.3527,  ..., 0.0812, 0.6959, 0.9329],
         [0.7419, 0.0588, 0.3261,  ..., 0.6794, 0.5393, 0.

In [190]:
x_original[0, 0, 0] = 122323
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(122323.), tensor(122323.))

In [194]:
## Indexing (selecting data from tensors), Indexing with pytorch is similar to indexing with numpy

In [198]:
x = torch.arange(1, 10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [200]:
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [202]:
# Let's index on our new tensor

In [204]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [206]:
# Let's index on middle bracker, dim = 1

In [208]:
x[0][0]

tensor([1, 2, 3])

In [210]:
# Let's index on most inner bracker(last dimention)

In [214]:
x[0][0][1]

tensor(2)

In [216]:
x[0][2][2]

tensor(9)

In [218]:
# You can also use ":" to select "all" of a target dimension

In [220]:
x[:, 0]

tensor([[1, 2, 3]])

In [222]:
# Get all values of 0th and 1st dims but only index 1 of 2 dims

In [224]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [226]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [228]:
# Get all values of the 0 dim but only the 1 index value of 1st and 2nd dim

In [246]:
x[:, 1, 1]

tensor([5])

In [248]:
# Get index 0 of 0th and 1st dim and all values of 2nd dim

In [256]:
x[0, 0, :]

tensor([1, 2, 3])

In [258]:
x[0, 1, :]

tensor([4, 5, 6])

In [260]:
# Index on x to return 9
# Index on x to reuturn 3, 6, 9

In [264]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [266]:
x[0, 2, 2]

tensor(9)

In [274]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [276]:
# Pytorch tensos and Numpy
# NumPy is a popular scientific python numerical computing library and because of this, 
# pytorch has functionality to interact with it

In [278]:
# Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
# PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [280]:
# Numpy array to tensor

In [284]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # when converting from numpy -> torch, pytorch reflects numpy's default datatype of float 64 unless specified otherwise float 32
tensor, array

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

In [286]:
# Change the value of array, what will this do to tensor

In [292]:
array = array + 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [295]:
# Tensor to Numpy

In [299]:
tensor = torch.ones(7)
tensor

tensor([1., 1., 1., 1., 1., 1., 1.])

In [301]:
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [303]:
# Change the tensor, what happens to numpy_tensor

In [305]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [309]:
# Reproducibility, trying to take the random out of random
# IN showr thow a neural network, learns

In [311]:
# Start with random numbers -> tensor operations -> update random numbers to try and make them of  better representations of the data -> again -> again -> again 

In [318]:
torch.rand(3, 3)

tensor([[0.1646, 0.8680, 0.0722],
        [0.4151, 0.4354, 0.0995],
        [0.6425, 0.1288, 0.6910]])

In [320]:
 # To reduce the randomness in neural networks and PyTorch comes the concept of a "Random Seed"

In [322]:
# Create two random tensors

In [328]:
random_tensor_a = torch.rand(3, 4)
random_tensor_b = torch.rand(3, 4)
print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.6087, 0.8195, 0.4285, 0.2239],
        [0.4620, 0.7238, 0.5150, 0.4032],
        [0.0479, 0.6901, 0.1663, 0.2149]])
tensor([[0.9452, 0.4584, 0.5908, 0.1907],
        [0.2047, 0.2808, 0.8885, 0.3853],
        [0.3294, 0.0947, 0.0587, 0.4122]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [330]:
# Let's make some random but reproducibile tensors

In [340]:
# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [343]:
# Running tensors and PyTorch objects on the GPU's (and making faster computations)

In [347]:
# CUDA, NVIDIA hardware + PyTorch working hebind the scenes to make everything hunky dory(good)

In [349]:
# 1. Google Colab is an options to use GPU
# 2. Use own GPU, take littble bit of setup

In [19]:
import tensorflow as tf
devices = tf.config.list_physical_devices()
print("\nDevices: ", devices)

gpus = tf.config.list_physical_devices('GPU')
if gpus:
  details = tf.config.experimental.get_device_details(gpus[0])
  print("GPU details: ", details)


Devices:  [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]


In [21]:
import torch

if torch.backends.mps.is_available():
   mps_device = torch.device("mps")
   x = torch.ones(1, device=mps_device)
   print (x)
else:
   print ("MPS device not found.")

tensor([1.], device='mps:0')


In [27]:
# GPU
import time
start_time = time.time()

# syncrocnize time with cpu, otherwise only time for oflaoding data to gpu would be measured
torch.mps.synchronize()

a = torch.ones(4000,4000, device="mps")
for _ in range(200):
   a +=a

elapsed_time = time.time() - start_time
print( "GPU Time: ", elapsed_time)

GPU Time:  0.15363001823425293


In [30]:
torch.cuda.is_available()

False

In [32]:
# Setup Device agnostic code

In [36]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [38]:
# Count number of devices

In [40]:
torch.cuda.device_count()

0

In [42]:
torch.backends.mps.is_available()

True

In [46]:
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'mps'

In [48]:
# Putting tensors (and models) on the GPU or MPS

In [50]:
# Create a tensor (default on the CPU)

In [56]:
tensor = torch.tensor([1,2,3], device="cpu") 
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [67]:
tensor = torch.tensor([1,2,3], device="mps")
tensor, tensor.device

(tensor([1, 2, 3], device='mps:0'), device(type='mps', index=0))

In [ ]:
# move tensor to GPU or MPS

In [71]:
tensor_on_gpu_or_mps = tensor.to(device)
tensor_on_gpu_or_mps

tensor([1, 2, 3], device='mps:0')

In [73]:
# Moving tensor back to the CPU

In [75]:
# If tensor is on GPU, can't transform it to NumPy

In [79]:
tensor_on_gpu_or_mps.numpy()

TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [81]:
# To fix the GPU/MPS tensor with NumPy issue, we can first set it to the CPU

In [87]:
tensor_back_on_cpu = tensor_on_gpu_or_mps.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [89]:
tensor_on_gpu_or_mps

tensor([1, 2, 3], device='mps:0')